config/routes.rb
Rails.application.routes.draw do
  get "/privacy", to: "static_pages#privacy"
  get "/terms", to: "static_pages#terms"
  get "/how-it-works", to: "static_pages#how_it_works"
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [ :index, :show, :destroy ]
  resource  :password, only: [ :edit, :update ]
  namespace :identity do
    resource :email,              only: [ :edit, :update ]
    resource :email_verification, only: [ :show, :create ]
    resource :password_reset,     only: [ :new, :edit, :create, :update ]
  end
  get  "/auth/failure",            to: "sessions/omniauth#failure"
  get  "/auth/:provider/callback", to: "sessions/omniauth#create"
  post "/auth/:provider/callback", to: "sessions/omniauth#create"
  get "up" => "rails/health#show", as: :rails_health_check
  resources :startups do
    member do
      post :like
    end
  end
  root "startups#index"
  get "search", to: "startups#search", as: :search
  resources :roles do
    member do
      get :confirm_applicant
    end
    resources :applications, only: [ :create ]
  end

  match "*path", to: "application#render_not_found", via: :all
end

app/models/startup.rb
class Startup < ApplicationRecord
  belongs_to :user

  acts_as_taggable_on :tags
  has_many :likes, dependent: :destroy
  has_many :roles, dependent: :destroy

  validates :name, presence: true
  validates :description, presence: true, length: { minimum: 25, maximum: 500 }
  validates :roles, length: { minimum: 1, message: "must have at least one role" }

  validates :website_url, format: { with: URI::DEFAULT_PARSER.make_regexp("https"), allow_blank: true }
  validates :instagram_url, format: { with: /\Ahttps?:\/\/(www\.)?instagram\.com\//i, allow_blank: true, message: "must be an Instagram URL" }
  validates :twitter_url,   format: { with: /\Ahttps?:\/\/(www\.)?twitter\.com\//i, allow_blank: true, message: "must be a Twitter URL" }
  validates :linkedin_url,  format: { with: /\Ahttps?:\/\/(www\.)?linkedin\.com\//i, allow_blank: true, message: "must be a LinkedIn URL" }
  validates :github_url,    format: { with: /\Ahttps?:\/\/(www\.)?github\.com\//i, allow_blank: true, message: "must be a GitHub URL" }
  validates :discord_url,   format: { with: /\Ahttps?:\/\/(www\.)?discord\.(gg|com)\//i, allow_blank: true, message: "must be a Discord invite or server URL" }

  def self.ransackable_attributes(auth_object = nil)
    %w[name description created_at]
  end

  def liked_by?(user)
    user && likes.exists?(user_id: user.id)
  end
end

app/controllers/startups_controller.rb
class StartupsController < ApplicationController
  before_action :set_startup, only: [ :show, :like, :edit, :update, :destroy ]
  skip_before_action :authenticate, only: [ :index, :show, :search ]

  def index
    @q = Startup.ransack(params[:q])
    @startups = @q.result(distinct: true).order(created_at: :desc)
  end

  def search
    @q = Startup.ransack(params[:q])
    @startups = @q.result(distinct: true)
  end

  def new
    @startup = Startup.new
  end

  def edit
    unless @startup.user == Current.user
      redirect_to root_path, alert: "You can only edit your own startups."
    end
  end


  def update
    unless @startup.user == Current.user
      redirect_to root_path, alert: "You can only update your own startups."
      return
    end

    if @startup.update(startup_params.except(:role_names))
      submitted_titles = (startup_params[:role_names] || "").split(",").map(&:strip).uniq
      @startup.roles.where.not(title: submitted_titles).destroy_all

      existing_titles = @startup.roles.pluck(:title)
      (submitted_titles - existing_titles).each do |title|
        @startup.roles.create(title: title, status: :open)
      end
      redirect_to @startup, notice: "Startup was successfully updated."
    else
      flash.now[:alert] = "There was an error updating the startup."
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    unless @startup.user == Current.user
      redirect_to root_path, alert: "You can only delete your own startups."
      return
    end

    @startup.destroy
    redirect_to startups_path, notice: "Startup was successfully deleted."
  end

  def create
    @startup = Startup.new(startup_params.except(:role_names))
    @startup.user = Current.user
      if startup_params[:role_names].present?
        role_titles = startup_params[:role_names].split(",")
        role_titles.each do |title|
          @startup.roles.build(title: title.strip, status: :open) # or your default status
        end
      end
    if @startup.save
      redirect_to root_path, notice: "Startup was successfully created."
    else
      flash.now[:alert] = "There was an error creating the startup."
      render :new, status: :unprocessable_entity
    end
  end

  def show
  end

  def like
    like = @startup.likes.find_by(user_id: Current.user.id)
    if like
      like.destroy
      @startup.reload
      respond_to do |format|
        format.turbo_stream
        format.json { render json: { liked: false, count: @startup.likes.count } }
      end
    else
      @startup.likes.create(user_id: Current.user.id)
      @startup.reload
      respond_to do |format|
        format.turbo_stream
        format.json { render json: { liked: true, count: @startup.likes.count } }
      end
    end
  end

  private
  def startup_params
    params.require(:startup).permit(:name,
                                    :description,
                                    :tag_list,
                                    :role_names,
                                    :website_url,
                                    :instagram_url,
                                    :twitter_url,
                                    :linkedin_url,
                                    :github_url,
                                    :discord_url)
  end

  def set_startup
    @startup = Startup.find(params[:id])
  end
end

app/helpers/startups_helper.rb
module StartupsHelper
end

app/views/startups/_actions.html.erb
<% if Current.user && (Current.user == startup.user) %>
  <div class="flex gap-5 items-center my-2 justify-end">
    <%= link_to 'Edit Startup', edit_startup_path(startup), class: button_classes.render %>
    <%= link_to 'Delete Startup', startup, method: :delete, data: {turbo_method: :delete, turbo_confirm: "Are you sure to delete #{startup.name}?"}, class: "bg-red-400 text-red-400 hover:bg-red-400 #{button_classes.render} " %>
  </div>
<% end %>

app/views/startups/_apply_button.html.erb
<% if role.taken? %>
  <span class="font-semibold">Taken</span>
<% elsif Current.user && role.startup.user == Current.user %>
  <span class="font-semibold"><%= pluralize(role.applicants.count, "applicant") %></span>
<% elsif Current.user && role.applicants.include?(Current.user) %>
  <span class="font-semibold">Applied</span>
<% else %>
  <% if Current.user %>
    <%= button_to "Apply", role_applications_path(role), method: :post, class: button_classes.render %>
  <% else %>
    <span class="font-medium">Open (sign in to apply)</span>
  <% end %>
<% end %>

app/views/startups/_like.html.erb
<turbo-frame id="like_frame_<%= startup.id %>">
  <% liked = startup.liked_by?(Current.user) %>
  <%= button_to(
        like_startup_path(startup),
        method: :post,
        form: { data: { turbo: "true" } },
        class: button_classes.render(variant: (liked ?  :invert : :base))
      ) do %>
    <%= raw "&#128077;" %>
    <span class="ml-2"><%= startup.likes.count %> likes</span>
  <% end %>
</turbo-frame>

app/views/startups/_social_links.html.erb
<div class="flex flex-col gap-2 text-sm">
  <% unless startup.website_url.blank? %>
    <%= link_to 'Visit Website', startup.website_url, class: "hover:underline" %>
  <% end %>
  <% unless startup.instagram_url.blank? %>
    <%= link_to 'Instagram', startup.instagram_url, class: "hover:underline" %>
  <% end %>
  <% unless startup.twitter_url.blank? %>
    <%= link_to 'Twitter', startup.twitter_url, class: "hover:underline" %>
  <% end %>
  <% unless startup.linkedin_url.blank? %>
    <%= link_to 'LinkedIn', startup.linkedin_url, class: "hover:underline" %>
  <% end %>
  <% unless startup.github_url.blank? %>
    <%= link_to 'GitHub', startup.github_url, class: "hover:underline" %>
  <% end %>
  <% unless startup.discord_url.blank? %>
    <%= link_to 'Discord', startup.discord_url, class: "hover:underline" %>
  <% end %>
</div>

app/views/startups/edit.html.erb
<div class="container mx-auto p-6 lg:px-8">
  <div class="md:flex md:items-center md:justify-between">
    <div class="min-w-0 flex-1">
      <h2 class="text-2xl/7 font-bold sm:truncate sm:text-3xl sm:tracking-tight">Post your startup</h2>
      <p class="mt-2 text-base/6 text-black">Showcase your dream here and get others excited to work with you.</p>
    </div>
  </div>
  <%= form_with(model: @startup) do |form| %>
    <% if @startup.errors.any? %>
      <div class="mb-6 rounded-sm border-2 border-red-500  p-4 text-black">
        <h3 class="font-semibold">Please fix the following errors:</h3>
        <ul class="mt-2 list-disc list-inside">
          <% @startup.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="mt-8 space-y-6">
      <div>
        <%= form.label :name, class: "block text-sm font-medium" %>
        <%= form.text_field :name, class: input_classes.render %>
      </div>
      <div>
        <%= form.label :description, class: "block text-sm font-medium" %>
        <%= form.text_area :description, rows: 5, class: input_classes.render %>
      </div>
      <div>
        <%= form.label :tag_list, "Tags" %>
        <div class="flex items-center">
          <%= form.text_field :tag_list, value: @startup.tag_list.join(", "), placeholder: "Get some AI buzzwords in here to build hype...", class: "tag-input #{input_classes.render}", data: { controller: "tag", action: "keydown->tag#preventEnter" } %>
        </div>
      </div>
      <div>
        <%= form.label :role_names, "Collaborators" %>
        <div class="flex items-center">
          <%= form.text_field :role_names, value: @startup.roles.map(&:title).join(','), placeholder: "Need a tech guru? Designer?", class: "tag-input #{input_classes.render}", data: { controller: "tag", action: "keydown->tag#preventEnter" } %>        </div>
      </div>
      <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div class="flex flex-col gap-2">
          <%= form.label :website_url, "Website (optional)", class: "block text-sm font-medium" %>
          <%= form.url_field :website_url, class: input_classes.render, placeholder: "https://your-startup-website.com" %>
        </div>
        <div class="flex flex-col gap-2">
          <%= form.label :instagram_url, "Instagram (optional)", class: "block text-sm font-medium" %>
          <%= form.url_field :instagram_url, class: input_classes.render, placeholder: "https://instagram.com/yourstartup" %>
        </div>
        <div class="flex flex-col gap-2">
          <%= form.label :twitter_url, "X (optional)", class: "block text-sm font-medium" %>
          <%= form.url_field :twitter_url, class: input_classes.render, placeholder: "https://x.com/yourstartup" %>
        </div>
        <div class="flex flex-col gap-2">
          <%= form.label :linkedin_url, "LinkedIn (optional)", class: "block text-sm font-medium" %>
          <%= form.url_field :linkedin_url, class: input_classes.render, placeholder: "https://linkedin.com/company/yourstartup" %>
        </div>
        <div class="flex flex-col gap-2">
          <%= form.label :github_url, "GitHub (optional)", class: "block text-sm font-medium" %>
          <%= form.url_field :github_url, class: input_classes.render, placeholder: "https://github.com/yourstartup" %>
        </div>
        <div class="flex flex-col gap-2">
          <%= form.label :discord_url, "Discord (optional)", class: "block text-sm font-medium" %>
          <%= form.url_field :discord_url, class: input_classes.render, placeholder: "https://discord.gg/yourstartup" %>
        </div>
      </div>
      <div>
        <%= form.submit "Edit Startup", class: button_classes.render %>
      </div>
    <% end %>
  </div>

app/views/startups/index.html.erb
<div class="container mx-auto p-6 lg:px-8">
  <div class="md:flex md:items-center md:justify-between">
    <div class="min-w-0 flex-1">
      <h2 class="text-2xl/7 font-bold sm:truncate sm:text-3xl sm:tracking-tight">Find or Join Early-Stage Startups</h2>
      <p class="mt-2 text-base/6 text-black">Discover innovative startups, connect with founders, and explore exciting opportunities in the startup ecosystem.</p>
    </div>
  </div>
  <div>
    <div class="mt-4 flex items-center gap-2 justify-between">
      <%= search_form_for @q, url: search_path, method: :get, html: { class: 'w-full flex items-center gap-2 justify-between' } do |f| %>
        <div class="grid grid-cols-1 flex-1 ">
          <%= f.search_field :name_cont, class: "col-start-1 row-start-1 pl-10 #{input_classes.render}", placeholder: "Search epic ideas..." %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="pointer-events-none col-start-1 row-start-1 ml-3 size-5 self-center text-black sm:size-4">
            <path stroke-linecap="round" stroke-linejoin="round" d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z" />
          </svg>
        </div>
        <%= f.submit 'Search', class: button_classes.render %>
      <% end %>
    </div>
  </div>
  <main class="mt-8 space-y-6">
    <h2 class="text-2xl/7 font-bold sm:truncate sm:text-3xl sm:tracking-tight">Newest startups</h2>
    <% if @startups.empty? %>
      <div class="text-center text-black">
        <p class="text-lg font-semibold">No startups found!</p>
        <p class="mt-2">¯\_(ツ)_/¯</p>
      </div>
    <% end %>
    <% @startups.each do |startup| %>
      <div class="border cursor-pointer rounded-sm border-black p-6 w-full bg-white block no-underline">
        <%= link_to startup_path(startup), class: "block no-underline" do %>
          <div class="flex items-center gap-2 mb-2">
            <span class="text-xl">🚀</span>
            <span class="font-semibold text-lg"><%= startup.name %></span>
          </div>
          <div class="mb-2 text-sm text-black">
            <%= startup.description %>
          </div>
          <% if startup.tags.present? %>
            <div class="mb-1 text-sm">
              <span class="font-medium">🏷 Tags:</span>
              <% colors = ["#2196F3", "#FF3D00", "#00E676", "#FFEB3B", "#6200EA"] %>
              <% startup.tags.each_with_index do |tag, i| %>
                <span class="rounded-sm inline-block px-2 py-1 mr-1 mb-1 text-xs font-semibold text-black" style="background-color: <%= colors[i % colors.size] %>;">
                  <%= tag %>
                </span>
              <% end %>
            </div>
          <% end %>
          <div class="text-xs text-black">
            🕒 Submitted <%= time_ago_in_words(startup.created_at) %> ago
          </div>
        <% end %>
        <div class="flex items-center gap-2 mt-2">
          <%= render 'startups/like', startup: startup %>
        </div>
      </div>
    <% end %>
  </main>
</div>

app/views/startups/like.turbo_stream.erb
  <meta name="turbo-visit-control" content="reload">
<turbo-stream action="replace" target="like_frame_<%= @startup.id %>">
  <template>
    <%= render partial: 'startups/like', formats: [:html], locals: { startup: @startup } %>
  </template>
</turbo-stream>

app/views/startups/new.html.erb
<div class="container mx-auto p-6 lg:px-8">
  <div class="md:flex md:items-center md:justify-between">
    <div class="min-w-0 flex-1">
      <h2 class="text-2xl/7 font-bold sm:truncate sm:text-3xl sm:tracking-tight">Post your startup</h2>
      <p class="mt-2 text-base/6 text-black">Showcase your dream here and get others excited to work with you.</p>
    </div>
  </div>
  <%= form_with(model: @startup) do |form| %>
    <% if @startup.errors.any? %>
      <div class="mb-6 rounded-sm border-2 border-red-500  p-4 text-black">
        <h3 class="font-semibold">Please fix the following errors:</h3>
        <ul class="mt-2 list-disc list-inside">
          <% @startup.errors.full_messages.each do |message| %>
            <li><%= message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div class="mt-8 space-y-6">
      <div>
        <%= form.label :name, class: "block text-sm font-medium" %>
        <%= form.text_field :name, class: input_classes.render %>
      </div>
      <div>
        <%= form.label :description, class: "block text-sm font-medium" %>
        <%= form.text_area :description, rows: 5, class: input_classes.render %>
      </div>
      <div>
        <%= form.label :tag_list, "Tags" %>
        <div class="flex items-center">
          <%= form.text_field :tag_list, value: @startup.tag_list.join(", "), placeholder: "Get some AI buzzwords in here to build hype...", class: "tag-input #{input_classes.render}", data: { controller: "tag", action: "keydown->tag#preventEnter" } %>
        </div>
      </div>
      <div>
        <%= form.label :role_names, "Collaborators" %>
        <div class="flex items-center">
          <%= form.text_field :role_names, value: @startup.roles.map(&:title).join(','), placeholder: "Need a tech guru? Designer?", class: "tag-input #{input_classes.render}", data: { controller: "tag", action: "keydown->tag#preventEnter" } %>        </div>
      </div>
      <div class="grid grid-cols-1 md:grid-cols-2 gap-4">
        <div class="flex flex-col gap-2">
          <%= form.label :website_url, "Website (optional)", class: "block text-sm font-medium" %>
          <%= form.url_field :website_url, class: input_classes.render, placeholder: "https://your-startup-website.com" %>
        </div>
        <div class="flex flex-col gap-2">
          <%= form.label :instagram_url, "Instagram (optional)", class: "block text-sm font-medium" %>
          <%= form.url_field :instagram_url, class: input_classes.render, placeholder: "https://instagram.com/yourstartup" %>
        </div>
        <div class="flex flex-col gap-2">
          <%= form.label :twitter_url, "Twitter (optional)", class: "block text-sm font-medium" %>
          <%= form.url_field :twitter_url, class: input_classes.render, placeholder: "https://twitter.com/yourstartup" %>
        </div>
        <div class="flex flex-col gap-2">
          <%= form.label :linkedin_url, "LinkedIn (optional)", class: "block text-sm font-medium" %>
          <%= form.url_field :linkedin_url, class: input_classes.render, placeholder: "https://linkedin.com/company/yourstartup" %>
        </div>
        <div class="flex flex-col gap-2">
          <%= form.label :github_url, "GitHub (optional)", class: "block text-sm font-medium" %>
          <%= form.url_field :github_url, class: input_classes.render, placeholder: "https://github.com/yourstartup" %>
        </div>
        <div class="flex flex-col gap-2">
          <%= form.label :discord_url, "Discord (optional)", class: "block text-sm font-medium" %>
          <%= form.url_field :discord_url, class: input_classes.render, placeholder: "https://discord.gg/yourstartup" %>
        </div>
      </div>
      <div>
        <%= form.submit "Create Startup", class: button_classes.render %>
      </div>
    <% end %>
  </div>

app/views/startups/search.html.erb
<div class="container mx-auto p-6 lg:px-8">
  <div class="md:flex md:items-center md:justify-between">
    <div class="min-w-0 flex-1">
      <h2 class="text-2xl/7 font-bold sm:truncate sm:text-3xl sm:tracking-tight">Search Results</h2>
    </div>
  </div>
  <div>
    <div class="mt-4 flex items-center gap-2 justify-between">
      <%= search_form_for @q, url: search_path, method: :get, html: { class: 'w-full flex items-center gap-2 justify-between', data: { controller: 'auto-submit', turbo_permanent: true } } do |f| %>
        <div class="grid grid-cols-1 flex-1 ">
          <%= f.search_field :name_cont, class: "col-start-1 row-start-1 pl-10 #{input_classes.render}", placeholder: "Search epic ideas...", data: { action: 'keyup->auto-submit#submit' }, autofocus: true %>
          <svg xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" class="pointer-events-none col-start-1 row-start-1 ml-3 size-5 self-center text-black sm:size-4">
            <path stroke-linecap="round" stroke-linejoin="round" d="m21 21-5.197-5.197m0 0A7.5 7.5 0 1 0 5.196 5.196a7.5 7.5 0 0 0 10.607 10.607Z" />
          </svg>
        </div>
        <%= f.submit 'Search', class: button_classes.render %>
      <% end %>
    </div>
  </div>
  <main class="mt-8 space-y-6">
    <% if @startups.empty? %>
      <div class="text-center text-black">
        <p class="text-lg font-semibold">No startups found!</p>
        <p class="mt-2">Maybe you should make one?</p>
        <p class="mt-2">¯\_(ツ)_/¯</p>
      </div>
    <% end %>
    <% @startups.each do |startup| %>
      <div class="border cursor-pointer rounded-sm border-black p-6 w-full bg-white block no-underline">
        <%= link_to startup_path(startup), class: "block no-underline" do %>
          <div class="flex items-center gap-2 mb-2">
            <span class="text-xl">🚀</span>
            <span class="font-semibold text-lg"><%= startup.name %></span>
          </div>
          <div class="mb-2 text-sm text-black">
            <%= startup.description %>
          </div>
          <% if startup.tags.present? %>
            <div class="mb-1 text-sm">
              <span class="font-medium">🏷 Tags:</span>
              <% colors = ["#2196F3", "#FF3D00", "#00E676", "#FFEB3B", "#6200EA"] %>
              <% startup.tags.each_with_index do |tag, i| %>
                <span class="rounded-sm inline-block px-2 py-1 mr-1 mb-1 text-xs font-semibold text-black" style="background-color: <%= colors[i % colors.size] %>;">
                  <%= tag %>
                </span>
              <% end %>
            </div>
          <% end %>
          <div class="text-xs text-black">
            🕒 Submitted <%= time_ago_in_words(startup.created_at) %> ago
          </div>
        <% end %>
        <div class="flex items-center gap-2 mt-2">
          <%= render 'startups/like', startup: startup %>
        </div>
      </div>
    <% end %>
  </main>
</div>

app/views/startups/show.html.erb
<div class="container mx-auto px-6 py-8 lg:px-8">
  <%= render 'actions', startup: @startup %>
  <div class="bg-white border border-black p-6 rounded-xs">
    <div class="flex justify-between items-center mb-6">
      <div>
        <h1 class="text-2xl font-bold text-black"><%= @startup.name %></h1>
        <p class="mt-1 text-sm text-black max-w-xl"><%= @startup.description %></p>
        <div class="mt-2 flex gap-2">
          <% @startup.tags.each do |tag| %>
            <span class="bg-black text-white text-xs font-bold px-3 py-1 rounded-sm"><%= tag %></span>
          <% end %>
        </div>
      </div>
      <%= render 'social_links', startup: @startup %>
    </div>
    <div class="space-y-4">
      <% @startup.roles.each do |role| %>
        <div class="flex justify-between items-center border p-4 rounded-sm ">
          <div class="flex items-center gap-4">
            <div>
              <h2 class="text-lg font-bold "><%= role[:title] %></h2>
              <p class="text-base font-medium text-black"><%= role[:desc] %></p>
            </div>
          </div>
          <%= render 'apply_button', startup: @startup, role: role %>
        </div>
      <% end %>
    </div>
  </div>
</div>