config/routes.rb
Rails.application.routes.draw do
  get "/privacy", to: "static_pages#privacy"
  get "/terms", to: "static_pages#terms"
  get "/how-it-works", to: "static_pages#how_it_works"
  get  "sign_in", to: "sessions#new"
  post "sign_in", to: "sessions#create"
  get  "sign_up", to: "registrations#new"
  post "sign_up", to: "registrations#create"
  resources :sessions, only: [ :index, :show, :destroy ]
  resource  :password, only: [ :edit, :update ]
  namespace :identity do
    resource :email,              only: [ :edit, :update ]
    resource :email_verification, only: [ :show, :create ]
    resource :password_reset,     only: [ :new, :edit, :create, :update ]
  end
  get  "/auth/failure",            to: "sessions/omniauth#failure"
  get  "/auth/:provider/callback", to: "sessions/omniauth#create"
  post "/auth/:provider/callback", to: "sessions/omniauth#create"
  get "up" => "rails/health#show", as: :rails_health_check
  resources :startups do
    member do
      post :like
    end
  end
  root "startups#index"
  get "search", to: "startups#search", as: :search
  resources :roles do
    member do
      get :confirm_applicant
    end
    resources :applications, only: [ :create ]
  end

  match "*path", to: "application#render_not_found", via: :all
end

app/views/shared/_alert.html.erb
<% if alert %>
  <div class="max-w-xl mx-auto">
    <div class="flex items-center mx-auto justify-center rounded-sm border-2 border-red-500 text-black">
      <p class="font-semibold text-lg p-4">
        <%= flash[:alert]  %>
      </p>
    </div>
  </div>
<% end %>

app/views/shared/_nav_bar.html.erb
<header class="bg-white ">
  <nav class="mx-auto flex max-w-7xl items-center justify-between p-6 lg:px-8" aria-label="Global">
    <%= link_to root_path, class: "-m-1.5 p-1.5" do %>
      <span class="sr-only">Hunterr</span>
      <svg width="200" height="60" xmlns="http://www.w3.org/2000/svg">
        <text x="0" y="45" font-family="Arial, Helvetica, sans-serif" font-size="40" font-weight="bold" fill="black">
          Hunterr
        </text>
      </svg>
    <% end %>
    <div class="flex flex-1 gap-2 items-center md:gap-5 justify-end">
      <%= link_to 'How it works', how_it_works_path, class: "text-sm/6 font-semibold hover:underline" %>
      <%= link_to 'Explore Startups', search_path, class: "text-sm/6 font-semibold hover:underline" %>
      <%= link_to 'Submit Startup', new_startup_path, class: "text-sm/6 font-semibold hover:underline" %>
      <% if Current.user %>
        <%= button_to 'Logout', session_path(Current.session.id), method: :delete, class: button_classes.render %>
      <% else %>
        <%= link_to 'Login', sign_in_path, class: button_classes.render %>
      <% end %>
    </div>
  </nav>
</header>

app/views/shared/_notice.html.erb
<% if notice %>
  <div class="max-w-xl mx-auto">
    <div class="flex items-center mx-auto justify-center rounded-sm border-2 border-green-500 text-black">
      <p class="font-semibold text-lg p-4">
        <%= flash[:notice]  %>
      </p>
    </div>
  </div>
<% end %>